'use client';

import { useAppStore } from '@/lib/store';
import { Ruler, Download, Info } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { cmToInches } from '@/lib/utils';

export function MeasurementPanel() {
  const { roomAnalysis, placements, selectedPlacementId } = useAppStore();

  const selectedPlacement = placements.find((p) => p.id === selectedPlacementId);

  const handleExportPDF = () => {
    // In production, this would call the backend to generate a PDF
    alert('Hanging guide PDF export will be generated by the backend service.');
  };

  return (
    <div className="flex flex-col h-full overflow-y-auto">
      <div className="p-4 border-b border-border">
        <h2 className="font-semibold text-lg">Measurements</h2>
        <p className="text-sm text-muted-foreground mt-1">
          Real-world dimensions and hanging guide
        </p>
      </div>

      <div className="p-4 space-y-4">
        {/* Wall Dimensions */}
        {roomAnalysis && (
          <div className="p-3 rounded-lg border border-border">
            <h3 className="text-sm font-medium flex items-center gap-2 mb-2">
              <Ruler className="h-4 w-4" />
              Wall Dimensions
            </h3>
            <div className="grid grid-cols-2 gap-3">
              <div>
                <p className="text-xs text-muted-foreground">Width</p>
                <p className="text-sm font-medium">
                  {roomAnalysis.wall_dimensions.width_cm} cm
                  <span className="text-muted-foreground ml-1">
                    ({cmToInches(roomAnalysis.wall_dimensions.width_cm).toFixed(1)}&quot;)
                  </span>
                </p>
              </div>
              <div>
                <p className="text-xs text-muted-foreground">Height</p>
                <p className="text-sm font-medium">
                  {roomAnalysis.wall_dimensions.height_cm} cm
                  <span className="text-muted-foreground ml-1">
                    ({cmToInches(roomAnalysis.wall_dimensions.height_cm).toFixed(1)}&quot;)
                  </span>
                </p>
              </div>
            </div>
          </div>
        )}

        {/* Selected Artwork Dimensions */}
        {selectedPlacement && (
          <div className="p-3 rounded-lg border border-primary/30 bg-primary/5">
            <h3 className="text-sm font-medium mb-2">Selected Artwork</h3>
            <p className="text-xs text-muted-foreground mb-2">{selectedPlacement.artworkTitle}</p>
            <div className="grid grid-cols-2 gap-3">
              <div>
                <p className="text-xs text-muted-foreground">Width</p>
                <p className="text-sm font-medium">
                  {selectedPlacement.realWorldSize.widthCm} cm
                  <span className="text-muted-foreground ml-1">
                    ({cmToInches(selectedPlacement.realWorldSize.widthCm).toFixed(1)}&quot;)
                  </span>
                </p>
              </div>
              <div>
                <p className="text-xs text-muted-foreground">Height</p>
                <p className="text-sm font-medium">
                  {selectedPlacement.realWorldSize.heightCm} cm
                  <span className="text-muted-foreground ml-1">
                    ({cmToInches(selectedPlacement.realWorldSize.heightCm).toFixed(1)}&quot;)
                  </span>
                </p>
              </div>
            </div>
          </div>
        )}

        {/* Placement Guide */}
        <div className="p-3 rounded-lg border border-border">
          <h3 className="text-sm font-medium mb-2">Hanging Guide</h3>
          <div className="space-y-2 text-xs text-muted-foreground">
            <div className="flex items-start gap-2">
              <Info className="h-3 w-3 mt-0.5 shrink-0 text-primary" />
              <p>Center of artwork should be at eye level (57&quot; from floor for residential)</p>
            </div>
            <div className="flex items-start gap-2">
              <Info className="h-3 w-3 mt-0.5 shrink-0 text-primary" />
              <p>For above furniture: 6-8&quot; above the top of the furniture piece</p>
            </div>
            <div className="flex items-start gap-2">
              <Info className="h-3 w-3 mt-0.5 shrink-0 text-primary" />
              <p>Gallery walls: maintain 2-3&quot; spacing between frames</p>
            </div>
          </div>
        </div>

        {/* All Placements */}
        {placements.length > 0 && (
          <div>
            <h3 className="text-sm font-medium mb-2">All Placements ({placements.length})</h3>
            <div className="space-y-2">
              {placements.map((placement, index) => (
                <div
                  key={placement.id}
                  className={`p-2 rounded-md border text-xs ${
                    placement.id === selectedPlacementId
                      ? 'border-primary bg-primary/5'
                      : 'border-border'
                  }`}
                >
                  <p className="font-medium">#{index + 1} {placement.artworkTitle}</p>
                  <p className="text-muted-foreground mt-0.5">
                    {placement.realWorldSize.widthCm}×{placement.realWorldSize.heightCm} cm •{' '}
                    {placement.frame.style.replace('_', ' ')}
                  </p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Export Button */}
        <Button onClick={handleExportPDF} className="w-full gap-2" variant="outline">
          <Download className="h-4 w-4" />
          Export Hanging Guide PDF
        </Button>
      </div>
    </div>
  );
}
